services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dayquest-algorithm
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    pull_policy: build
    tty: true      
    stdin_open: true
networks:
  dayquest-network:
    external: true
    name: dayquest-network