services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dayquest-algorithm
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    pull_policy: build
    tty: true      
    stdin_open: true
    networks:
      - dayquest-network

networks:
  dayquest-network:
    external: true
    name: dayquest-network